apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: postgres
labels:
  app: postgres
data:
  POSTGRES_DB: stateful-flask-db
  POSTGRES_USER: stateful-flask-user
  POSTGRES_PASSWORD: stateful-flask-password
