apiVersion: v1
kind: Service
metadata:
  name: stateful-flask
  namespace: stateful-flask
spec:
  selector:
    app: stateful-flask
  ports:
  - name: http
    protocol: TCP
    port: 5000
    targetPort: 5000

